version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec pumactl start"
    stdin_open: true
    tty: true
    volumes:
      - .:/fingers_sky
      - sockets:/fingers_sky/tmp/sockets
    ports:
      - "3000:3000"
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    volumes: 
      - sockets:/fingers_sky/tmp/sockets
    depends_on: 
      - app

volumes:
  db_data:
  sockets:
